---
# tag::app-deployment[]
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  labels:
    app: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
        - name: app
          image: quay.io/service-binding/spring-petclinic:latest
          imagePullPolicy: Always
          env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: spring-petclinic
                key: spring_profile
                optional: true
          - name: PETCLINIC_FEATURES
            valueFrom:
              configMapKeyRef:
                name: spring-petclinic
                key: petclinic_features
                optional: true
          ports:
          - name: http
            containerPort: 8080
# end::app-deployment[]
---
# tag::app-service[]
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-petclinic
  name: spring-petclinic
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: spring-petclinic
# end::app-service[]
