# tag::service-binding[]
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name:
    spring-petclinic-keycloak
spec:
  services:
    - group: apps
      version: v1
      kind: Deployment
      name: spring-petclinic-keycloak
    - group: ""
      version: v1
      kind: Secret
      name: spring-petclinic-keycloak
  application:
    name: spring-petclinic
    group: apps
    version: v1
    resource: deployments
# end::service-binding[]
